services:
  - type: web
    name: hotel-erp-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
